spring:
  datasource:
    url: jdbc:mysql://101.132.104.41:3306/jiayin_sys?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: jiayin
    password: jiayin@20201024